server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javacourse?serverTimezone=UTC
    username: p3
    password: p3
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    hibernate:
      ddl-auto: update

#VM Option
#-Dcom.sun.management.jmxremote.port=8080
#-Dcom.sun.management.jmxremote.authenticate=false
#-Dcom.sun.management.jmxremote.ssl=false