server:
  port: 8080
spring:
  thymeleaf:
    prefix: file:src/main/resources/templates
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/javaCourse?serverTimezone=UTC
    username: root
    password: group25/17
